.ALIASES
R_R1            R1(1=0 2=OUT ) CN @TEST14.SCHEMATIC1(sch_1):INS44@ANALOG.R.Normal(chips)
L_L1            L1(1=IN 2=N05727 ) CN @TEST14.SCHEMATIC1(sch_1):INS5599@ANALOG.L.Normal(chips)
V_V1            V1(+=IN -=0 ) CN @TEST14.SCHEMATIC1(sch_1):INS121@SOURCE.VAC.Normal(chips)
C_C1            C1(1=N05727 2=OUT ) CN @TEST14.SCHEMATIC1(sch_1):INS5692@ANALOG.C.Normal(chips)
_    _(in=IN)
_    _(out=OUT)
.ENDALIASES
