.ALIASES
Q_Q1            Q1(c=VOUT b=VBE e=0 ) CN @1-3.SCHEMATIC1(sch_1):I00040@BIPOLAR.Q2N2222.Normal(chips)
V_Vcc           Vcc(+=N00135 -=0 ) CN @1-3.SCHEMATIC1(sch_1):I00081@SOURCE.VDC.Normal(chips)
R_R1            R1(1=N00112 2=VBE ) CN @1-3.SCHEMATIC1(sch_1):I00106@ANALOG_P.r.Normal(chips)
R_R2            R2(1=VOUT 2=N00135 ) CN @1-3.SCHEMATIC1(sch_1):INS1340@ANALOG_P.r.Normal(chips)
V_Vbb           Vbb(+=N00112 -=0 ) CN @1-3.SCHEMATIC1(sch_1):I01135@SOURCE.VDC.Normal(chips)
_    _(Vout=VOUT)
_    _(vbe=VBE)
.ENDALIASES
